INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (1, 'Psicologia', 'Ricardo Gonçalves') ON DUPLICATE KEY UPDATE ID=1 ;
INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (2, 'Geriatria', 'Marília Guimarães') ON DUPLICATE KEY UPDATE ID=2 ;
INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (3, 'Homeopatia', 'Gustavo Peixoto Lemos') ON DUPLICATE KEY UPDATE ID=3 ;
INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (4, 'Anestesiologia', 'Laura Seles Pacó dos Santos') ON DUPLICATE KEY UPDATE ID=4 ;
INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (5, 'Cardiologia', 'Juliana Seles da Rocha') ON DUPLICATE KEY UPDATE ID=5 ;
INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (6, 'Cancerologia', 'Olavo Seles Pacó dos Santos') ON DUPLICATE KEY UPDATE ID=6;
INSERT INTO medico (ID, ESPECIALIDADE,NOME) VALUES (7, 'Cancerologia', 'Mariana Juliano') ON DUPLICATE KEY UPDATE ID=7 ;


INSERT INTO usuario(ID,SENHA,USUARIO,ID_MEDICO) VALUES (1, 'senhamedico','medico@email.com', 1) ON DUPLICATE KEY UPDATE ID=1 ;
INSERT INTO usuario(ID,SENHA,USUARIO,ID_MEDICO) VALUES (2, 'senhamedico2','medico2', 2) ON DUPLICATE KEY UPDATE ID=2 ;
INSERT INTO usuario(ID,SENHA,USUARIO,ID_MEDICO) VALUES (3, 'senhamedico3','medico3', 3) ON DUPLICATE KEY UPDATE ID=3 ;


INSERT INTO paciente(ID,CPF,IDADE,NOME,TELEFONE) VALUES ('AB2', '52844116','35', 'Maria José Silvestre','3388-4251') ON DUPLICATE KEY UPDATE ID='AB2';
INSERT INTO paciente(ID,CPF,IDADE,NOME,TELEFONE) VALUES ('AB23', '54755444','48','José Gomes Vieira',' 2255-2141') ON DUPLICATE KEY UPDATE ID='AB23';
INSERT INTO paciente(ID,CPF,IDADE,NOME,TELEFONE) VALUES ('AB24', '15442222','17','Margarete Menezes', '3355-8547') ON DUPLICATE KEY UPDATE ID='AB24';

